### ISSUE TITLE
[🐛] node >= 10

### ISSUE THREAD

**Issue by Spown** [snyk/snyk#1699] opened 2021-03-08 20:26 UTC
So it's not a bug per se, more of a version mismanagement issue... I just spent 3 hours looking into why appveyor fails to build and test my projects. The immediate culprit was ``chalk``:

```
error chalk@4.1.0: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"
```

``chalk`` was introduced through ``@snyk/inquirer@^7.3.3-patch`` in ``snyk@1.455.0``. [``snyk@1.455.0``](https://github.com/snyk/snyk/commit/92645c55d06c91596c40db534c869fb6d0b0a651) is also the version, that silently, yet officially dropped ``node@8``. Which would be fine, but installing ``snyk@1.454.0`` or ``snyk@1.453.0`` still results in a [dep that requires ``@snyk/inquirer@^7.3.3-patch``](https://github.com/snyk/snyk/blob/v1.453.0/package.json#L71) (it is ``>=8``, that still introduces ``chalk@4.1.0`` with ``>=10``). I don't get how your versioning works, frankly. Everything is this ``1.0.0-monorepo``.

Could you please add a small node version compatibility table into README, like:

Snyk|Node
-|-
``^1.455.0``|``>=10``
``>= ??? && <=1.454``|``>=8``

and also ensure that it represents the reality?

Thank you in advance.

**Comment by Spown** [comment] 2021-03-08 20:52
the first time ``chalk@4.1.0` appears in ``snyk@1.392.0`` - so this is the actual ``node>=10`` version.

**Comment by Spown** [comment] 2021-03-09 17:56
locally yarn@1.22.5, Travis uses yarn@1.22.4. Appveyor is glitching with my project right now, so it doesn't matter.

Additionally, I've found many more dep. modules that require ``node@>=10`` even in ``snyk@1.391``, introduced through other deps. Like for example [this build](https://travis-ci.org/github/Spown/i18n-node/jobs/762021261) uses ``snyk@1.391`` and fails at ``mkdirp@1.0.4`` that comes from ``snyk-docker-plugin@3.19.0``. Right now I was able to [successfully build](https://travis-ci.org/github/Spown/i18n-node/jobs/762050112) for ``node@8`` with ``snyk@1.300``. Ergo the actual version jump accours somewhere between 1.300 and 1.392.0.

**Comment by JackuB** [comment] 2021-03-19 09:20
If this is concerning yarn, then this is pretty much a duplicate of https://github.com/snyk/snyk/issues/1270

We were testing CLI working on Node 8 with npm, where `engines.node` incompatibility results only in a warning. Yarn considers these strict and fails. Since a few months ago, we are testing Snyk CLI installation with yarn as well: https://github.com/snyk/snyk/blob/2f1326c13cff6daa07de5ac5521465446cb53581/.github/workflows/smoke-tests.yml#L19 but only for Node.js versions >=10.

As a result, getting Snyk CLI working with Yarn AND Node.js 8, you need to use the [`--ignore-engines` flag](https://classic.yarnpkg.com/en/docs/cli/install/#toc-yarn-install-ignore-engines).

**Closed by JackuB** 2021-03-19 09:20 UTC

**Comment by Spown** [comment] 2021-03-19 10:01
> As a result, getting Snyk CLI working with Yarn AND Node.js 8, you need to use the --ignore-engines flag.

As I was able to find a Snyk version installable through yarn for Node@8 (namely Snyk@1.319.1) - my concern was not the ability to install, but rather ensuring other people could as well. So I wasn't asking how to use yarn - I know how to ignore engines and I don't want to ignore them and risk to catch a major bug through actual deps only to be able to install a devDep of supplementary value.

Neither do I ask for some sort of backwards compatibility...

So again, whether you will or wont support and/or test for node@8 in the future is kinda irrelevant. I am speaking of the past versions of Snyk that definetly do support previous versions of Node and ware tested for it at time of release. I suggest these should be mentioned in the README.

Anyway, thank you.
