### ISSUE TITLE
Snyk protect fails with "Internal error (reference: d627e8ec-3eea-4327-af3f-a8cf74ae5824)"[🐛]

### ISSUE THREAD

**Issue by unandyala** [snyk/snyk#1378] opened 2020-09-01 20:35 UTC
- `node -v`: v12.16.3
- `npm -v`: 6.14.4
- `snyk -v`: 1.387.0
- OS: (e.g. OSX, Linux, Windows, ...) macOS Mojave 10.14.6
- Command run: (e.g. `snyk test --all-projects`, `snyk protect`, ...) snyk protect

### Expected behaviour
 `snyk protect` to run to completion with out errors

### Actual behaviour
`synk protect` fails with 
Internal error (reference: 71963bae-49ff-4bd0-8a6b-99d1c7b78628)
After debugging, found the following  specific request is failing with this error 
https://snyk.io/api/v1/vuln/npm/patches 

### Debug log
```bash
$ snyk protect --debug
  snyk protect { _: [ [Circular] ], debug: true, callGraphBuilderTimeout: '300' } +0ms
  snyk ~~~~ LIVE RUN ~~~~ +0ms
  snyk Potential policy locations found: [sdk project dir
  '/commerce-sdk',
  '/commerce-sdk/node_modules/@commerce-apps/core',
  '/commerce-sdk/node_modules/snyk-docker-plugin',
  '/commerce-sdk/node_modules/snyk-go-plugin'
] +0ms
  snyk:find-files Encountered multiple node lockfiles files, defaulting to /Users//WebstormProjects/commerce-sdk/package-lock.json +0ms
  snyk sending request to: https://snyk.io/api/v1/vuln/npm/patches +0ms
  snyk request body size: 2262027 +0ms
  snyk gzipped request body size: 107882 +0ms
  snyk not using proxy +12ms
  snyk:run-test Error running test {..
  error: InternalServerError: Internal server error
      at handleTestHttpErrorResponse (/Users//.nvm/versions/node/v12.16.3/lib/node_modules/snyk/src/lib/snyk-test/run-test.ts:303:13)
      at /Users//.nvm/versions/node/v12.16.3/lib/node_modules/snyk/src/lib/snyk-test/run-test.ts:278:21
      at module.exports (/Users//.nvm/versions/node/v12.16.3/lib/node_modules/snyk/src/lib/request/index.ts:16:7)
      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
    code: 500,
    innerError: undefined,
    userMessage: 'Internal error (reference: 89d05fe8-3cd0-4211-b071-0e4d7d9cf772)',
    strCode: 'INTERNAL_SERVER_ERROR'
  }
} +0ms
FailedToRunTestError: Internal error (reference: 89d05fe8-3cd0-4211-b071-0e4d7d9cf772)
    at runTest (/Users//.nvm/versions/node/v12.16.3/lib/node_modules/snyk/src/lib/snyk-test/run-test.ts:171:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  snyk analytics {
  args: [ { debug: true, callGraphBuilderTimeout: '300' } ],
  command: 'bad-command',
  org: undefined,
  metadata: {
    local: [ true, true ],
    'generating-node-dependency-tree': { lockFile: false, targetFile: 'package-lock.json' },
    pluginName: 'snyk-nodejs-lockfile-parser',
    policies: 4,
    policyLocations: [
      '/commerce-sdk',
      '/commerce-sdk/node_modules/@commerce-apps/core',
      '/commerce-sdk/node_modules/snyk-docker-plugin',
      '/commerce-sdk/node_modules/snyk-go-plugin'
    ],
    packageManager: 'npm',
    packageName: 'commerce-sdk',
    packageVersion: '2.0.0',
    package: 'commerce-sdk@2.0.0',
    depGraph: false,
    isDocker: false,
    payloadSize: 2262027,
    gzippedPayloadSize: 107882,
    success: false,
    'error-message': 'Internal error (reference: 89d05fe8-3cd0-4211-b071-0e4d7d9cf772)',
    error: 'FailedToRunTestError: Internal error (reference: 89d05fe8-3cd0-4211-b071-0e4d7d9cf772)\n' +
      '    at runTest (/Users//.nvm/versions/node/v12.16.3/lib/node_modules/snyk/src/lib/snyk-test/run-test.ts:171:11)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:97:5)',
    'error-code': 500,
    command: 'protect'
  },
  version: '1.387.0',
  os: 'macOS Mojave',
  nodeVersion: 'v12.16.3',
  standalone: false,
  integrationName: '',
  integrationVersion: '',
  id: '452c43eaf4c9109f4efad0760247d5a0e61911f9',
  ci: false,
  durationMs: 2406
} +0ms

  snyk Exit code: 2 +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +537ms
  snyk request body size: 1400 +0ms
  snyk gzipped request body size: 678 +0ms
  snyk not using proxy +0ms
```

**Comment by JackuB** [comment] 2020-09-01 21:03
Hi, thanks for reporting this. It's an internal error on our side. We've identified where it's coming from ad will update here once we know more.

**Comment by unandyala** [comment] 2020-09-02 03:01
Thanks for the update

**Comment by unandyala** [comment] 2020-09-02 14:43
Hi @JackuB, 
Other members in my team are not seeing this issue. I am wondering what could be the reason and is there a work around until this is fixed

**Comment by lili2311** [comment] 2020-09-04 09:33
hi @unandyala please could you confirm that you are part of a Snyk org? Ir looks like you may not be and the flow fails. You can also pass the org to the Snyk commands by adding `--org=Org_Name`. *You may* have to login to Snyk first to ensure you are in at least one organisation or ask your group admin to assigned to an org you should be part of.

**Comment by unandyala** [comment] 2020-09-04 16:03
Yes I am part of the organization. I can login into the Snyk GUI using SSO and see all the projects under the org. When I try using  --org, I see the below error
```
 Please check the version and package name and try running `snyk test` again.
For additional assistance, run `snyk help` or check out our docs
(link to: https://support.snyk.io/hc/en-us/articles/360003851277#UUID-ba99a73f-110d-1f1d-9e7a-1bad66bf0996).
```

**Comment by lili2311** [comment] 2020-09-04 16:28
👋 Please could you raise an issue to support@snyk.io so we can chat more there so we can share more sensitive logs we see :) I am not seeing you belong to an org on the request you are making so let's sort this out there.

**Comment by erichusband** [comment] 2020-09-04 16:57
Hi there! I had a quick look, and you probably don't know this but you actually have two accounts - one using your SSO (where you can see all of your organizations orgs) and another one using Github-auth that you don't seem to have logged into and created an org with yet.

The problem is that your Snyk CLI is using the token from your Github-auth account, which doesn't have permission to access all of your organizations data.

I'd suggest logging in with your saml SSO auth provider, and navigating to https://app.snyk.io/account to grab your proper CLI token. You can then authenticate in your CLI with `snyk auth <token>` This will allow the command to pass.

**Comment by unandyala** [comment] 2020-09-04 17:25
Its working. Thanks

**Closed** 2020-09-08 15:00 UTC
Labels: :hatching_chick:  in progress
