### ISSUE TITLE
Builds with "snyk protect" failing on appveyor

### ISSUE THREAD

**Issue by nicolindemann** [Snyk/snyk#32] opened 2016-07-06 18:48 UTC
- `node -v`: various 
- `npm -v`: various
- `snyk -v`: 1.16.0

### Expected behaviour

Successful build likes on Travis CI (e.g. https://travis-ci.org/proux/rage4service/builds/142716359)

### Actual behaviour

All Builds are failing through a ENOENT error.

### Steps to reproduce

Using appveyor (e.g. https://ci.appveyor.com/project/nicolindemann/rage4service/build/25) with the "snyk protect"-command.

**Comment by guypod** [comment] 2016-07-06 22:21
Thanks for reporting this. 
I managed to reproduce this on a fork of your project: https://ci.appveyor.com/project/guypod/rage4service/build/job/w9cxo0wrjvybt222

Will dig deeper and get back to you shortly.

**Comment by guypod** [comment] 2016-07-07 09:49
@nicolindemann FYI, we think we found the cause of this, has to do with semicolon in filenames. It was fixed in the past, but somehow crept back in. Expecting to have a fix today, stay tuned.

**Closed** 2016-07-07 12:38 UTC

**Comment by remy** [comment] 2016-07-07 12:39
This has been marked as closed, but it will need to be released first. A dependency that Snyk uses needed the fix. I'll post here with the version of Snyk CLI that ensures this fix is live.

**Comment by guypod** [comment] 2016-07-07 17:36
Now released. To use the fix, you'll need to update the `package.json` file on `rage4service` to use snyk version `^1.17.0` (we're updating our new PRs to do so).

Thanks for catching the issue!
