### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by Hongbo-Miao** [snyk/snyk#753] opened 2019-08-28 21:08 UTC
- `node -v`: 10.16.1
- `npm -v`: 6.11.1
- `snyk -v`: 1.221.1
- Command run: `snyk monitor` or `snyk monitor --debug`

### Expected behaviour
Show me results

### Actual behaviour

For `synk monitor`, it shows

![image](https://user-images.githubusercontent.com/3375461/63893224-72d3a700-c99e-11e9-9c26-4459581ff49e.png)

> Monitoring /Users/hongbo-miao/Clouds/Git/hongbomiao.com...
> 
> Connection timeout.

For `synk monitor --debug`, it shows

![image](https://user-images.githubusercontent.com/3375461/63893199-5df71380-c99e-11e9-8d42-56f00cc308ae.png)

> (base)  ✘ ✝  Clouds/Git/hongbomiao.com   master  snyk monitor --debug
>   snyk monitor { _: [ [Circular] ], debug: true } +0ms
>   snyk Analyzing npm dependencies for /Users/hongbo-miao/Clouds/Git/hongbomiao.com/yarn.lock +0ms
>   snyk sending request to: https://snyk.io/api/v1/monitor/yarn +0msbomiao.com/yarn.lock
>   snyk request body size: 80571347 +0ms
>   snyk gzipped request body size: 1669553 +0ms
>   snyk not using proxy +1ms
> Error:
> Monitoring /Users/hongbo-miao/Clouds/Git/hongbomiao.com...
> 
> Connection timeout.
>     at /Users/hongbo-miao/.config/yarn/global/node_modules/snyk/src/cli/commands/monitor.ts:257:9
>     at Generator.throw (<anonymous>)
>     at rejected (/Users/hongbo-miao/.config/yarn/global/node_modules/snyk/dist/cli/commands/monitor.js:5:65)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>   snyk analytics { args: [ { debug: true } ],
>   command: 'bad-command',
>   metadata:
>    { packageManager: [ 'yarn', 'yarn' ],
>      pluginOptions: { debug: true },
>      local: true,
>      'generating-node-dependency-tree': { lockFile: true, targetFile: 'yarn.lock' },
>      pluginName: 'snyk-nodejs-lockfile-parser',
>      isDocker: false,
>      targetBranch: 'master',
>      payloadSize: 80571347,
>      gzippedPayloadSize: 1669553,
>      'error-message':
>       '\nMonitoring /Users/hongbo-miao/Clouds/Git/hongbomiao.com...\n\nConnection timeout.',
>      error:
>       'Error: \nMonitoring /Users/hongbo-miao/Clouds/Git/hongbomiao.com...\n\nConnection timeout.\n    at /Users/hongbo-miao/.config/yarn/global/node_modules/snyk/src/cli/commands/monitor.ts:257:9\n    at Generator.throw (<anonymous>)\n    at rejected (/Users/hongbo-miao/.config/yarn/global/node_modules/snyk/dist/cli/commands/monitor.js:5:65)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
>      'error-code': undefined,
>      command: 'monitor' },
>   version: '1.221.1',
>   os: 'macOS Mojave',
>   nodeVersion: 'v10.16.1',
>   id: 'cfaa9fba2e21b79fc961b91c1d9765b7d15f7ef3',
>   ci: false,
>   durationMs: 312421 } +0ms
>   snyk sending request to: https://snyk.io/api/v1/analytics/cli +5m
>   snyk request body size: 1042 +0ms
>   snyk gzipped request body size: 563 +0ms
>   snyk not using proxy +1ms
> 
>   snyk Exit code: 2 +0ms

### Steps to reproduce

1. Clone https://github.com/Hongbo-Miao/hongbomiao.com
2. Run `snyk monitor`

**Comment by AndreDalcher** [comment] 2019-08-30 10:15
Hey,

Thanks for the bug report.

It looks like the issues is being caused by your project generating a very large dependency tree. We are doing some work to try and improve our performance in this area, but in the meantime could you try running this again with the `--prune-repeated-subdependencies` flag to avoid sending data about dependencies that appear multiple times - i.e. `snyk monitor --prune-repeated-subdependencies`

Hopefully this should resolve the issue for you.

**Comment by lili2311** [comment] 2019-10-11 12:30
👋 @Hongbo-Miao please could you confirm if this is now resolved for you?

**Comment by dkontorovskyy** [comment] 2019-11-04 11:36
@Hongbo-Miao please could you confirm if this is now resolved for you?

**Comment by lili2311** [comment] 2019-11-21 17:56
@Hongbo-Miao We will close this issue as we have not back fro a little while, please re-open if it is still an issue

**Closed by lili2311** 2019-11-21 17:56 UTC
Labels: :bug:  bug
