### ISSUE TITLE
alpine and linux binaries fail checksum

### ISSUE THREAD

**Issue by chrisdlangton** [snyk/snyk#633] opened 2019-07-04 13:20 UTC
to test;
```
wget -q -O - https://api.github.com/repos/snyk/snyk/releases/latest | grep browser_download_url | grep snyk-linux |cut -d : -f 2,3 | tr -d \" | xargs wget -q

if ! echo "$(cat snyk-linux.sha256)" | sha256sum -c -; then
    echo "Checksum failed" >&2
    exit 1
fi
```

**Comment by adrukh** [comment] 2019-07-06 05:31
Hmmm I'm actually getting this just fine on my end:
```
$ wget -q -O - https://api.github.com/repos/snyk/snyk/releases/latest | grep browser_download_url | grep snyk-linux |cut -d : -f 2,3 | tr -d \" | xargs wget -q
$ cat snyk-linux.sha256 | sha256sum -c -
snyk-linux: OK
```

Two options I can think of:
1. You had an instance of `snyk-linux` already downloaded, so the most recent `wget` created `snyk-linux.1`, and caused the sha256sum to mismatch.
2. We had a problem with an earlier version, but it is now gone. I just tested against `1.192.3`, can you see if this persists on your end?

**Comment by chrisdlangton** [comment] 2019-07-06 05:43
the version has bumped several times already so this issue seemed to have effected v`1.192.1` or one or more versions around that

**Comment by karniwl** [comment] 2019-09-01 15:29
Hi @chrisdlangton since you confirmed the issue was only around the version `1.192.1` I'm closing the issue. Please feel free to open new issues if you encounter this issue again or any other issue. Thank you!

**Closed by karniwl** 2019-09-01 15:29 UTC
Labels: :bug:  bug, alpine
