### ISSUE TITLE
[🐛]snyk v1.413: snyk auth errors with Cannot find module 'legacy-snyk-docker-plugin'

### ISSUE THREAD

**Issue by nicksimmonds-lmk** [snyk/snyk#1454] opened 2020-10-09 13:33 UTC
- `node -v`: 10.16.0
- `npm -v`: 6.9.0
- `snyk -v`: 1.413
- OS: Linux
- Command run: snyk auth
                           snyk -v
### Expected behaviour
To authenticate me.
To list the current installed version

### Actual behaviour
Error: Cannot find module 'legacy-snyk-docker-plugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/snyk/src/lib/plugins/index.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

### Steps to reproduce
run the cli command:
snyk auth xxxx
or
snyk -v

### Debug log
If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by JackuB** [comment] 2020-10-09 13:36
Duplicate of #1453 - closing this one, all updates will be in #1453

**Closed by JackuB** 2020-10-09 13:36 UTC
