### ISSUE TITLE
UTF-8 BOM in package.json causes failure to detect node project

### ISSUE THREAD

**Issue by focusaurus** [snyk/snyk#81] opened 2017-05-10 21:23 UTC
- `node -v`: 6.2.2
- `npm -v`: 3.9.5
- `snyk -v`: 1.30.0

- Command run: `snyk test`

### Expected behaviour
- Project recognized and scan proceeds

### Actual behaviour
- error message: `is not a node project`, no scan

### Steps to reproduce
- Save `package.json` as UTF-8 with a byte order mark (hex efbbbf) at the beginning
- Confirmed removing the BOM and re-running allows the scan to proceed and is an effective workaround

---

Note I investigated a little bit and it's something to do with how `node_modules/snyk-resolve-deps/lib/deps.js` and `tryRequire` work but I didn't track further than that.

**Comment by adrukh** [comment] 2017-05-11 09:58
@focusaurus thanks for reporting this!

I can reproduce the issue locally, thanks for the instructions (utf8 BOM is hex `efbbbf`).
Indeed a shortcoming - it is perfectly possible to `require('./package.json')` that includes a BOM, but we fail to process it properly.

I'll take a look and update once we have something, but cannot promise a concrete timeline right now.

**Comment by adrukh** [comment] 2018-06-12 11:43
@focusaurus the issue is now resolved for `package.json` files that include a UTF-8 BOM!
See https://github.com/snyk/snyk/releases/tag/v1.82.2

Thanks again to @dotboris for their contribution!

Please comment here confirming this change so we can close the issue.

**Closed** 2019-10-02 14:49 UTC
Labels: :bug:  bug
