### ISSUE TITLE
Invalid Version: https://registry.npmjs.org/archy/-/archy-1.0.0.tgz when snyk test

### ISSUE THREAD

**Issue by vivikenen** [snyk/snyk#147] opened 2018-04-09 06:33 UTC
- `node -v`: v6.11.0
- `npm -v`: 5.8.0
- `snyk -v`: 1.71.0
- Command run:
```
$ npm install -g snyk
/usr/local/bin/snyk -> /usr/local/lib/node_modules/snyk/cli/index.js
+ snyk@1.71.0
updated 1 package in 6.38s

$ snyk auth

Now redirecting you to our github auth page, go ahead and log in,
and once the auth is complete, return to this prompt and you'll
be ready to start using snyk.

Your account has been authenticated. Snyk is now ready to be used.

$ snyk test
Invalid Version: https://registry.npmjs.org/archy/-/archy-1.0.0.tgz
```
### Expected behaviour
I try to my friend's laptop, doing the exactly same things. snyk test works totally fine on my friend's laptop but not mine. Could anyone help me to figure out why it happens? Thanks~

---

**Comment by adrukh** [comment] 2018-04-09 06:35
@vivikenen thanks for reporting this!

We've seen this to occur due to incorrect `npm install` of the project being tested. Can you please delete `node_modules` and `npm install` over again, then try scanning with Snyk?

If the problem is persistent, please reach out to support@snyk.io so we can take a deeper look.

**Comment by vivikenen** [comment] 2018-04-09 07:45
thx @adrukh , it fixed now. everything works fine now

**Comment by adrukh** [comment] 2018-04-22 16:51
@vivikenen I'm closing this issue, please reopen if you have anything new on it.

**Closed by adrukh** 2018-04-22 16:51 UTC
